### ISSUE TITLE
Error: Call to undefined method Sofort\SofortLib\TransactionData::setTransaction() 

### ISSUE THREAD

**Issue by davalb** [sofort/sofortlib-php#10]
In the docblock of the TransactionData-class is the following example:

```
$SofortLibTransactionData = new SofortLibTransactionData('yourapikey');
$SofortLibTransactionData->setTransaction('1234-456-789654-31321')->sendRequest();
```

This example produces a `undefined method` error. The example seems to be broken or outdated.

**Comment by the-fruu** [comment]
Thanks for pointing us at this issue. I've corrected the docblock and took another look at the examples, docblocks and comments. As far as I am concerned everything should be fine after the #11 pull request was merged.

**Comment by davalb** [comment]
thanks!
