### ISSUE TITLE
Multiple Reasons do not work

### ISSUE THREAD

**Issue by benjaminpick** [sofort/sofortlib-php#13]
Probably the PHP Library do not format it the way the API likes it to have:

Example Request: 

``` php
$s = Sofortueberweisung('...');
///...
$s->setReason('Testueberweisung', 'Verwendungszweck', 'p1');
$s->setReason('Testueberweisung2', 'Verwendungszweck2', 'p2');
echo json_encode($s->getParameters());
```

outputs:

``` json
{
   "su":[

   ],
   "amount":56,
   "currency_code":"EUR",
   "sender":{
      "country_code":"DE"
   },
   "p1":{
      "reasons":{
         "reason":[
            "Testueberweisung",
            "Verwendungszweck"
         ]
      }
   },
   "p2":{
      "reasons":{
         "reason":[
            "Testueberweisung2",
            "Verwendungszweck2"
         ]
      }
   },
   "success_url":"...",
   "success_link_redirect":true,
   "abort_url":"...",
   "notification_urls":{
      "notification_url":[
         {
            "@data":"..."
         }
      ]
   }
}
```

The API returns as error messages:

``` php
array(2) {
  [0]=>
  array(3) {
    ["code"]=>
    string(4) "8054"
    ["message"]=>
    string(59) "All products deactivated due to errors, initiation aborted."
    ["field"]=>
    string(0) ""
  }
  [1]=>
  array(3) {
    ["code"]=>
    string(21) "8010.reasons.reason.1"
    ["message"]=>
    string(18) "Must not be empty."
    ["field"]=>
    string(16) "reasons.reason.1"
  }
}
```

**Comment by VasuLief** [comment]
Hello benjaminpick,

our Api looks for the reasons either in in the xml-root or in the 'su' subtree.
Can you try to skip the third parameter 'p1' or change it to 'su'?

`$s->setReason('Testueberweisung', 'Verwendungszweck');`

**Comment by benjaminpick** [comment]
Oh I see ... so this cannot be used for showing more product details on the payment page. Closing this then.

**Comment by wickowicz** [comment]
Hello! Can you explain how to initialize more than one product to add to payment in Sofort?
I thought it must be some like:

`$Sofortueberweisung->setReason('Testueberweisung', 'Verwendungszweck');
$Sofortueberweisung->setReason('Testueberweisung2', 'Verwendungszweck2');`

But it don't works. Give me some help, please.

**Comment by VasuLief** [comment]
I'm not sure if I understand what you want to achieve. What do you mean by "Product"? 

A single banking transaction consists of two reasons.

**Comment by wickowicz** [comment]
VasuLief, thank you for your answer. 
Look, I use Sofort as one of payment methods in internet store. And when buyer wants to buy more than one product (goods), I thought it can be displayed at Sofort payment page. For example like this:

![sofort-example](https://cloud.githubusercontent.com/assets/22521761/22942642/029447f8-f2f3-11e6-820e-07eaab427ba8.PNG)

It shows only one product (goods) at payment page, but if there are more than one product, is it possible to show them all at Sofort payment page? And how can I do it, using SofortLib?

Thanks a lot!

**Comment by VasuLief** [comment]
Such a feature is not possible right now. 
The reasons you set with setReason() are used by the bank as the reason for the transaction and usually contains some sort of identifier that you can use to reconcile that transaction.

**Comment by wickowicz** [comment]
VasuLief, okay. Thank you a lot!
