### ISSUE TITLE
Why is this notification URL not valid?

### ISSUE THREAD

**Issue by benjaminpick** [sofort/sofortlib-php#15]
As notification URL, I have set: `http://myhost.local/?id=535&type=4840&mail_id=837&success=notify`
Why does the API return : `8016.notification_urls.notification_url.1:Must be a valid URL.`?
- Is it because it is a different host than my sofort account?
- Or because it's not HTTPS?
- Or because it's not reachable from the internet? (dns resolve)
- Or simply because it contains '.local'? 

Of course I don't assume notification to work. But as I am developing on my local machine, I try to code as much as possible there before pushing it on the staging server. Please add more information to the API documentation which URL validation checks are in place.

**Comment by VasuLief** [comment]
Hello benjaminpick,

yes, you're correct, its because your host is not reachable from our dns server.

**Comment by 0x20h** [comment]
You can also leave out notifications if you are not retrieving them anyway.

**Comment by shoaibgits** [comment]
The Issues is with me i am trying to pass a URL like this and get the same error as above:

     $Sofortueberweisung->setNotificationUrl('http://localhost:8088/payment/success', 'received');

**Comment by VasuLief** [comment]
Local URLs are not allowed as we can't make calls to them.

**Comment by zaibigits099** [comment]
Changing Local Url to actual live url worked for me but i'm not getting any transaction Id in response of notification url ? or am I getting data the wrong way ?
