### ISSUE TITLE
Refund API: 5003 error

### ISSUE THREAD

**Issue by hypeJunction** [sofort/sofortlib-php#17]
I am seeing strange behavior from the Refund API. No matter what amount of the refund I set, I get the `5003 Amount must not exceed transaction amount.` error. 
I have verified that transaction exists and it's amount is 100 Eur. No matter if I set the amount to 1, 99, or 100 EUR, I get the same error. Am I missing something?

**Comment by hypeJunction** [comment]
I have also tried using strings, floats, ints with and without decimals. No difference.

**Comment by VasuLief** [comment]
What Version of the sofortlib are you using?

**Comment by hypeJunction** [comment]
From my composer.lock
```json
    {
            "name": "sofort/sofortlib-php",
            "version": "3.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/sofort/sofortlib-php.git",
                "reference": "35362fee0427d0811cbab0ba35435920b14f22d6"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/sofort/sofortlib-php/zipball/35362fee0427d0811cbab0ba35435920b14f22d6",
                "reference": "35362fee0427d0811cbab0ba35435920b14f22d6",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.10"
            },
            "require-dev": {
                "phpunit/phpunit": "~4.5.1"
            },
            "suggest": {
                "ext-curl": "*"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "Sofort\\SofortLib\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-3"
            ],
            "authors": [
                {
                    "name": "Sofort GmbH",
                    "email": "opensource@sofort.com"
                }
            ],
            "description": "SOFORT API wrapper for PHP",
            "time": "2016-11-22 14:45:03"
        }
```

**Comment by VasuLief** [comment]
There seems to be a issue in the release of 3.2.0, I'll look into it, meanwhile you can use version 3.1.0 until we release a fix for 3.2.0.

**Comment by hypeJunction** [comment]
Ok. Thanks. I will try that. 
Here is my code for reference: https://github.com/hypeJunction/Elgg-payments_sofort/blob/master/classes/hypeJunction/Payments/Sofort/Adapter.php#L218

**Comment by hypeJunction** [comment]
Doesn't seem to make any difference. Could it be a server-side issue?

**Comment by hypeJunction** [comment]
So, I have looked into my Sofort dashboard, and there was a prepared refund in there. So I suppose, it couldn't prepare it again. I have manually deleted it, and tried again, but now the Payment URL is empty.

**Comment by hypeJunction** [comment]
So, it seems your refunds example has mislead me. I thought that I would need to forward to sofort to complete the refund, but instead it just needed to be consolidated. I was testing the same transaction multiple times, and was getting an error because a refund was already there but unconsolidated.

**Comment by katzefudder** [comment]
I hope, everything's fine on your side?
Closing this issue for now.
Please don't hesitate to contact us again if there are any uncertainties, cheers :)

**Comment by hypeJunction** [comment]
Well, I would suggest you to update the example, so that it doesn't mislead people. Perhaps it would make sense to explain the refund workflow in a little more detail - the Refund API docs are not very straightforward. 
Thanks for your help anyway.
