### ISSUE TITLE
getTransactionId() not work correct

### ISSUE THREAD

**Issue by virdignus** [sofort/sofortlib-php#2]
hi, i don't understand what is going. Making file, based on examples, do request, after do getNotification(file_get_contents('php://input')). But if i trying  echo getTransactionId() it is empty, and output array

```
$output = array();
$methods = array(
    'getAmount' => '',
    'getAmountRefunded' => '',
    'getCount' => '',
    'getPaymentMethod' => '',
    'getConsumerProtection' => '',
    'getStatus' => '',
    'getStatusReason' => '',
    'getStatusModifiedTime' => '',
    'getLanguageCode' => '',
    'getCurrency' => '',
    'getTransaction' => '',
    'getReason' => array(0,0),
    'getUserVariable' => 0,
    'getTime' => '',
    'getProjectId' => '',
    'getRecipientHolder' => '',
    'getRecipientAccountNumber' => '',
    'getRecipientBankCode' => '',
    'getRecipientCountryCode' => '',
    'getRecipientBankName' => '',
    'getRecipientBic' => '',
    'getRecipientIban' => '',
    'getSenderHolder' => '',
    'getSenderAccountNumber' => '',
    'getSenderBankCode' => '',
    'getSenderCountryCode' => '',
    'getSenderBankName' => '',
    'getSenderBic' => '',
    'getSenderIban' => '',
);

foreach($methods as $method => $params) {
    if(count($params) == 2) {
        $output[] = $method . ': ' . $SofortLibTransactionData->$method($params[0], $params[1]);
    } else if($params !== '') {
        $output[] = $method . ': ' . $SofortLibTransactionData->$method($params);
    } else {
        $output[] = $method . ': ' . $SofortLibTransactionData->$method();
    }
}
```

 is empty. Can you explain this? 
Hope, You understand what i mean :)

**Comment by katzefudder** [comment]
First of all, I assume you do have an account within sofort.com (you registered as a merchant via https://www.sofort.com/eng-INT/merchant/sb/overview/) and have received a configuration key.
Given that, you could easily initiate transactions via SOFORT. Once a transaction has been initiated, you may receive information about it using _SofortLibTransactionData_.

The example for TransactionData misleads in some ways: it is supposed to work as an entry point e.g. in your web shop for automatically sent notifications by SOFORT via HTTP. Given that request enclosing a transaction id (e.g. _00907-01222-51ADD8C9-86C8_), the code in the mentioned example would issue a request pointing back to SOFORT to fetch additional information about that transaction.

This example is about fetching information about a given transaction id. It is supposed to work as an entry point to enable communication between your web instance and SOFORT. It's not completely functional when you simply execute the given code. It's just about giving you an idea on how to implement _TransactionData_.

I hope, my explanation helped you a little further. If there are any questions regarding usage and implementation, dont bother asking.

Cheers

**Comment by lxlang** [comment]
I assume that this Problem is solved.
