### ISSUE TITLE
autoload.php file is missing

### ISSUE THREAD

**Issue by masudewucse** [sofort/sofortlib-php#21]
I cant find the autoload.php. as a result the api is not working. can you please help?
Here are the errors:
`Warning: require(/www/webseiten/testing/sofort/examples/../vendor/autoload.php): failed to open stream: No such file or directory in /www/webseiten/testing/sofort/examples/Paycode.php on line 4

Fatal error: require(): Failed opening required '/www/webseiten/testing/sofort/examples/../vendor/autoload.php' (include_path='.:/usr/share/php') in /www/webseiten/testing/sofort/examples/Paycode.php on line 4`

**Comment by katzefudder** [comment]
Sofortlib relies on composer for handling dependencies (and composer's autoloading feature https://getcomposer.org/doc/01-basic-usage.md#autoloading)
Before using sofortlib, you have to fetch all dependencies (issuing `composer install`) supposing composer is installed and available.

**Comment by dhcmega** [comment]
Hi, I don't have SSH access to the server, is there any way in which I can manually create the autoload file? thanks

**Comment by katzefudder** [comment]
Unfortunately, we at this place cannot offer any help in integrating the software. Please reach out to integration@sofort.com and/or https://www.sofort.com/integrationCenter-eng-DE/integration/shopsysteme/

**Comment by fabian-mcfly** [comment]
It makes absolutely no sense to not offer a composer-independent version of the SofortLib since there are absolutely no dependencies.
