### ISSUE TITLE
Local development systems aren't supported

### ISSUE THREAD

**Issue by Sebbo94BY** [sofort/sofortlib-php#28]
I develop on my local machine. The same code, which is working on our STAGE and LIVE server, doesn't work in my local system, because the library can't resolve my local system URL like `https://my.shop.local/payment/notification`.

Due of that, I'm getting the following error:
```
"code" => "8016"
"message" => "Must be a valid URL."
"field" => "notification_urls.notification_url.1"
```

Is there a way to support local development?

// Edit: I'm talking about [SOFORT Überweisung](https://github.com/sofort/sofortlib-php/blob/master/examples/Sofortueberweisung.php).

**Comment by chklarna** [comment]
**Hey**, @Sebi94nbg ,

I'm sorry to say but we can not send our notifications to your local URL as it is no accessible address where we could send data to.

Greetings,
Chris

**Comment by Sebbo94BY** [comment]
Thanks for your feedback. I would understand, when everything except the notification would work, but it even does not redirect to the payment site.

Other payment solutions do also support local development. The only thing, what doesn't work is the POST request to the notification URL, because the API can't resolve the set domain.

But this would already help a lot to develop the most.

Does there any documentation exist, where I can see which data will be send by your API to my application? Some examples would be useful.

**Comment by chklarna** [comment]
Please take a look at our Developer API-Documentation:
https://www.sofort.com/integrationCenter-eng-DE/content/view/full/2513

Unfortunately you have to do some type of "live" testing.
The usual procedure of most of our merchants is to create a a test project or use their existing system in test mode to develop their integration.

Greetings,
Chris

**Comment by Sebbo94BY** [comment]
Thanks for the link to the documentation.

Mhmm, ok. You may find a better solution in future. This would be a great improvement.

**Comment by chklarna** [comment]
Thanks for your suggestion. We're discussing a proper solution for local development.
