### ISSUE TITLE
SOFORT Überweisung: Which transaction were aborted?

### ISSUE THREAD

**Issue by Sebbo94BY** [sofort/sofortlib-php#29]
I'm a bit confused with the process of [SOFORT Überweisung](https://github.com/sofort/sofortlib-php/blob/master/examples/Sofortueberweisung.php).

When I hit the "Cancel" button on the payment site, it redirects me to my set AbortURL, but I don't get any GET or POST information about the canceled payment. The Transaction ID would be already very nice - or any other custom key, which identifies which transaction were aborted.

Is there a way to get such information?

**Comment by chklarna** [comment]
**Hello** @Sebi94nbg ,
just add
`?transaction=-TRANSACTION-`
to the abort URL so you can access the Transaction ID via the get parameter transaction.

Greetings,
Chris

**Comment by Sebbo94BY** [comment]
So your API does autom. replace the "variable" `-TRANSACTION-` with the transaction ID?

**Comment by chklarna** [comment]
Yes, that is correct.

Greetings,
Chris

**Comment by Sebbo94BY** [comment]
Great. Thanks, this is very helpful!
