### ISSUE TITLE
TransactionData() only returns false

### ISSUE THREAD

**Issue by Sebbo94BY** [sofort/sofortlib-php#30]
I want to get the status of a specific transaction on the basis of a transaction ID.

This is my code:
```php
<?php
$config_key = '12345:123456:edc788a4316ce7e2ac0ede037aa623d7'; // I'm using my correct one; This is from your examples
$transaction_id = '00907-01222-51ADD8C9-86C8'; // I'm using a correct one; This is from your examples

$transaction_data = new TransactionData($config_key);
$transaction_data->addTransaction($transaction_id);
$transaction_data->setApiVersion('2.0');

$transaction_data->sendRequest();

if($transaction_data->isError()) {
	echo $transaction_data->getError();
} else {
	$output = array();

	$output[] = 'getStatus' . ': ' . $transaction_data->getStatus();
	$output[] = 'getStatusReason' . ': ' . $transaction_data->getStatusReason();

	echo implode('<br />', $output);
}
```

I always land in the `else` condition, so `$transaction_data->isError()` is always `false`. But unfortunately, `$transaction_data->getStatus()` is also only `false` - it doesn't contain any status.

What's my issue? Do I even use the correct code to archive my goal?

**Comment by 0x20h** [comment]
If the referenced transaction has not been finished successfully, you will not get any details. You can add the following check in the `else` block to find out:
```
    if (!$transaction_data->getCount()) {
        echo 'transaction not found!' . PHP_EOL;
        exit;
    }
```

**Comment by Sebbo94BY** [comment]
Ah, ok. So if somebody has aborted the transaction, there is no status like "transaction_canceled"?

ONLY when the transaction were successful - in form of a payment - there would be any details, right?

**Comment by 0x20h** [comment]
Correct. So you cannot really differentiate if a transaction id exists or has not been finished (yet) successfully. However, since you get the transaction id in the initiation call, you can infer that a transaction has not been finished if you don't get a result.

The safest/intended way to fetch the details is usually when you get a notification from our systems to synchronise the transaction state between your shop and our systems.

Does this answer your questions?

**Comment by Sebbo94BY** [comment]
Yes, this did answer my question. Thanks!

Just a quick confirmation question: The status code for a real successful payment is "received" with the status reason "credited", or? Only with this status, I have received the payment / money from the client, right?

**Comment by 0x20h** [comment]
@Sebi94nbg You can read about here: https://www.sofort.com/integrationCenter-eng-DE/content/view/full/2513#h5-5
