### ISSUE TITLE
cURL transport is insecure

### ISSUE THREAD

**Issue by willemstuursma** [sofort/sofortlib-php#31]
Hello! 

The cURL request uses insecure defaults. SSL is not verified at all. 

See https://github.com/sofort/sofortlib-php/blob/master/src/Sofort/SofortLib/HttpCurl.php#L55. 

The hostname in the certificate is not validated and the trustworthiness of the certificate is also not validated.

This allows mitm attacks and basically negates all protections offered by HTTPS.

**Comment by 0x20h** [comment]
Thanks for reporting!
