### ISSUE TITLE
Feature-Request: Please add IDENT API

### ISSUE THREAD

**Issue by gnanet** [sofort/sofortlib-php#8]
The latest german Youth Protection Act require shops to verify the age of visitors, if they are selling Alcohol, Tobacco, etc and the most mentioned "postident" way is no working solution for the web.

Because of the requirement, that already the browsing of an e-smoking webshop has to be denied to minors, the IDENT API seems to be a real alternative, and the only known implementation seems to be in xt:commerce

In my opinion, an open source implementation of this API would help the "Product" itself too, so i ask you to consider the inclusion of this API into the sofortlib-php.

**Comment by katzefudder** [comment]
Hi @gnanet 
Thank you for your interest in our products!
We have started an internal discussion about the so called "Jugendschutzgesetz" (German Youth Protection Act) and our product SOFORT Ident.
We came to the conclusion that our product meets the requirements of German law. Details about our product concerning security can be found on the following page https://www.sofort.com/eng-DE/merchant/si/security/

Although it seems quite handy to have an implementation, I'm afraid to tell you that we are currently not planning to implement SOFORT Ident into SofortLib.
Information about implementing SOFORT Ident by yourself can be found here https://www.sofort.com/eng-DE/merchant/si/integration/
